spring:
#  config:
#    activate:
#      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch_inflearn?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      # always : 스프링 부트 기본 테이블 자동 생성 (테스트,개발때만 사용)
      # never : 스프링 부트 기본 테이블 생성 안함 (운영 시 테이블은 schema-mysql.sql 이용해 직접 생성해 놓고 never로 세팅)
      initialize-schema: always
      # 배치 테이블 prefix를 변경 (기본값 BATCH_)
      # table-prefix: SYSTEM_
    job:
      # enabled: false일 경우 스프링 배치 실행 시 job 자동 실행 막기 (대신 Runner 만들어서 직접 실행해줘야함) (기본값 true)
      # enabled: false
      # Program arguments로 입력된 job을 실행한다. (--job.name=helloJob,simpleJob)
      names: ${job.name:NONE}

  # JPA Settings
  # ddl-auto : create, create-drop, validate, update, none
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
